<?php

function alapjarat_mc_menu() {

  $items['admin/config/alapjarat_mc'] = array(
    'title' => 'Alapjárat Media collection page settings',
    'description' => 'Labels, titles, etc.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('alapjarat_mc_admin'),
    'access arguments' => array('administer alapjarat_mc settings'),
    'type' => MENU_NORMAL_ITEM,
   );

    $items['media-collection/%'] = array(
        'title' => 'Alapjárat Média',
        'page callback' => 'alapjarat_mc_media_page',
        'page arguments' => array(1),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
        'menu_name' => 'main-menu',
    );

  return $items;
}

function alapjarat_mc_admin() {
  $form = array();

  $form['mc_header_menu_item_all'] = array(
    '#type' => 'textfield',
    '#title' => t('Media gallery header menu item "All"'),
    '#default_value' => variable_get('mc_header_menu_item_all', 'All'),
    '#description' => t("Media collection page header menu item title."),
    '#required' => TRUE,
  );

  $form['mc_header_menu_item_image'] = array(
    '#type' => 'textfield',
    '#title' => t('Media gallery header menu item "Images"'),
    '#default_value' => variable_get('mc_header_menu_item_image', 'Images'),
    '#description' => t("Media collection page header menu item title."),
    '#required' => TRUE,
  );

  $form['mc_header_menu_item_video'] = array(
    '#type' => 'textfield',
    '#title' => t('Media gallery header menu item "Videos"'),
    '#default_value' => variable_get('mc_header_menu_item_video', 'Videos'),
    '#description' => t("Media collection page header menu item title."),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

function alapjarat_mc_ctools_plugin_directory($owner, $plugin_type) {
	if ($owner == 'ctools' && $plugin_type == 'content_types') {
		return 'plugins/content_types';
	}
}

function alapjarat_mc_get_gallery_images($gid) {
  $query = db_select('field_data_field_gallery', 'fg');
  $query
  ->fields('fg', array('field_gallery_fid', 'delta'))
  ->condition('fg.entity_id', $gid, '=')
  ->condition('fg.delta', 0, '>')
  ->orderBy('fg.delta', 'ASC');
  $results = $query
  ->execute()
  ->fetchAll();

  $images = [];
  foreach ($results as $record) {
    $file = file_load($record->field_gallery_fid);
    $images[] = file_create_url($file->uri);
  }

  return $images;
}

function alapjarat_mc_collect_gallery_images() {

  if (isset($_GET['page'])) {
    $offset = $_GET['page'] * 10;
  } else {
    $offset = 0;
  }

  $query = db_select('field_data_field_gallery', 'fg');
  $query->leftJoin('node', 'n', 'n.nid = fg.entity_id');
  $query->leftJoin('field_data_field_title2', 'ft', 'ft.entity_id = fg.entity_id');
  $query
  ->fields('n', array('title', 'status', 'changed', 'nid'))
  ->fields('fg', array('field_gallery_fid', 'delta'))
  ->fields('ft', array('field_title2_value'))
  ->condition('n.status', 1, '=')
  ->condition('fg.delta', 0, '=')
  ->orderBy('n.changed', 'DESC')
  ->orderBy('fg.delta', 'ASC');
  $query->range($offset, 20);
  //$query->isNull('wp.entity_id');
  $results = $query
  ->execute()
  ->fetchAll();
  
  foreach ($results as $record) {
    $file = file_load($record->field_gallery_fid);
    $media[] = array(
      'type' => 'image',
      'title' => mb_substr(check_plain(strip_tags($record->field_title2_value)), 0, 30) . '...',
      'thumbnail' => theme('image_style', array('path' => $file->uri, 'style_name' => 'media_gallery_image')),
      'publishDate' => $record->changed,
      'destination' => file_create_url($file->uri),
      'siblings' => alapjarat_mc_get_gallery_images($record->nid),
      'groupName' => 'lightbox[g' . $record->nid . ']',
      'content' => $record->nid,
    );
  }

  /*
  $query = db_select('field_data_field_media', 'fg');
  $query->leftJoin('node', 'n', 'n.nid = fg.entity_id');
  $query->leftJoin('field_data_field_title2', 'ft', 'ft.entity_id = fg.entity_id');
  $query
  ->fields('n', array('title', 'status', 'changed', 'nid'))
  ->fields('fg', array('field_media_fid'))
  ->fields('ft', array('field_title2_value'))
  ->condition('n.status', 1, '=')
  ->orderBy('n.changed', 'DESC');
  $query->range($offset, 10);
  //$query->isNull('wp.entity_id');
  $results = $query
  ->execute()
  ->fetchAll();

  foreach ($results as $record) {
    $file = file_load($record->field_media_fid);
    $media[] = array(
      'type' => 'image',
      'title' => mb_substr(check_plain(strip_tags($record->field_title2_value)), 0, 30) . '...',
      'thumbnail' => theme('image_style', array('path' => $file->uri, 'style_name' => 'media_gallery_image')),
      'publishDate' => $record->changed,
      'destination' => file_create_url($file->uri),
      'groupName' => 'lightbox',
      'content' => $record->nid,
    );
  }
  */
  return $media;
}

function alapjarat_mc_collect_youtube_channel_videos() {
  $apikey = 'AIzaSyDuKd3sYC5jGDOZC49hnt4XtGOH8uz7p34';
  $channelid = 'UCueleOZ2QFAaVSHXheZlFig'; // alapjarat
  $playlistid = 'UUueleOZ2QFAaVSHXheZlFig';

  $urltemplate = "https://www.googleapis.com/youtube/v3/search?key=AIzaSyDuKd3sYC5jGDOZC49hnt4XtGOH8uz7p34&channelId=###channelID###&part=snippet,id&order=date&maxResults=9";
  $urltemplate = "https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=$playlistid&key=$apikey&maxResults=20&order=date";

  if (isset($_GET['npt'])) {
    $pageToken = $_GET['npt'];
    $urltemplate .= "&pageToken=$pageToken";
  }

  if (isset($_GET['ppt'])) {
    $pageToken = $_GET['ppt'];
    $urltemplate .= "&pageToken=$pageToken";
  }

  $response = _alapjarat_mc_curl_get_contents($urltemplate);

  foreach ($response['items'] as $video) {
    $media[] = array(
      'type' => 'video',
      'title' => mb_substr($video['snippet']['title'], 0, 30) . '...',
      'thumbnail' => $video['snippet']['thumbnails']['medium'],
      'publishDate' => strtotime($video['snippet']['publishedAt']),
      'destination' => 'https://www.youtube.com/embed/' . $video['snippet']['resourceId']['videoId'],
    );
  }

  return $media;
}

function _alapjarat_mc_get_pager_tokens() {
  $apikey = 'AIzaSyDuKd3sYC5jGDOZC49hnt4XtGOH8uz7p34';
  $channelid = 'UCueleOZ2QFAaVSHXheZlFig'; // alapjarat
  $playlistid = 'UUueleOZ2QFAaVSHXheZlFig';

  $urltemplate = "https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=$playlistid&key=$apikey&maxResults=20&order=date";

  if (isset($_GET['npt'])) {
    $pageToken = $_GET['npt'];
    $urltemplate .= "&pageToken=$pageToken";
  }

  if (isset($_GET['ppt'])) {
    $pageToken = $_GET['ppt'];
    $urltemplate .= "&pageToken=$pageToken";
  }

  $response = _alapjarat_mc_curl_get_contents($urltemplate);

  return array(
    'nextPageToken' => isset($response['nextPageToken']) ? $response['nextPageToken'] : NULL,
    'prevPageToken' => isset($response['prevPageToken']) ? $response['prevPageToken'] : NULL,
  );
}

function alapjarat_mc_merged_media($type = 'all') {
  
  $images = [];
  if ($type == 'all' || $type == 'image') {
    $images = alapjarat_mc_collect_gallery_images();
  }

  $videos = [];
  if ($type == 'all' || $type == 'video') {
    $videos = alapjarat_mc_collect_youtube_channel_videos();
  }

  $all_media = array_merge($images, $videos);
  usort($all_media, function($a, $b) {
    return $b['publishDate'] - $a['publishDate'];
  });      

  return $all_media;
}

function alapjarat_mc_media_page($type = 'all') {
  drupal_add_css(drupal_get_path('module', 'alapjarat_mc') .'/alapjarat_mc.css', array('scope' => 'header'));
  drupal_add_js(drupal_get_path('module', 'alapjarat_mc') .'/alapjarat_mc.js', array('scope' => 'header'));

  $all_media = alapjarat_mc_merged_media($type);
  foreach ($all_media as $media) {
  	if ($media['type'] == 'image') {
  	  $output[] = theme('alapjarat_mc_image', array('item' => $media));
  	}
  	if ($media['type'] == 'video') {
  	  $output[] = theme('alapjarat_mc_video', array('item' => $media));
  	}
  }

  $page_template = file_get_contents(drupal_get_path('module', 'alapjarat_mc') .'/alapjarat_mc_page.tpl.php');
  $content = implode('', $output);
  $page = str_replace('###content###', $content, $page_template);

  // Header menu items.
  $page = str_replace('###header_menu_all###', t(variable_get('mc_header_menu_item_all', 'All')), $page);
  $page = str_replace('###header_menu_image###', t(variable_get('mc_header_menu_item_image', 'Images')), $page);
  $page = str_replace('###header_menu_video###', t(variable_get('mc_header_menu_item_video', 'Videos')), $page);

  // Header menu active item.
  $classes_all = ['menu-item-link'];
  $classes_image = ['menu-item-link'];
  $classes_video = ['menu-item-link'];
  switch (arg(1)) {
    case 'all': $classes_all[] = 'active';
      break;
    case 'image': $classes_image[] = 'active';
      break;
    case 'video': $classes_video[] = 'active';
      break;
  }

  $page = str_replace('###classes_all###', implode(' ', $classes_all), $page);
  $page = str_replace('###classes_image###', implode(' ', $classes_image), $page);
  $page = str_replace('###classes_video###', implode(' ', $classes_video), $page);

  $pager_tokens = _alapjarat_mc_get_pager_tokens();

  if (isset($_GET['page'])) {
    if ($_GET['page'] > 1) {
      $prevpage = '&page=' . ($_GET['page'] * 1 - 1);
    } else {
      $prevpage = '';
    }
    $nextpage = '&page=' . ($_GET['page'] * 1 + 1);
  } else {
    $nextpage = '&page=2';
  }

  if (!is_null($pager_tokens['nextPageToken'])) {
    $next_page = '<a href="/media-collection/' . arg(1) . '?npt=' . $pager_tokens['nextPageToken'] . $nextpage . '">'. t('next') . '</a>';
  }
  if (!is_null($pager_tokens['prevPageToken'])) {
    $prev_page = '<a href="/media-collection/' . arg(1) . '?ppt=' . $pager_tokens['prevPageToken'] . $prevpage . '">' . t('previous') . '</a>';
  }
  
  $page = str_replace('###pager-next###', $next_page, $page);
  $page = str_replace('###pager-prev###', $prev_page, $page);

  return $page;
}

function _alapjarat_mc_curl_get_contents($url){
  $ch = curl_init($url);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
  curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
  curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
  $data = curl_exec($ch);
  curl_close($ch);
  $data = json_decode($data, true);
  return $data;
}

function alapjarat_mc_theme() {
   return array(
     'alapjarat_mc_image' => array(
       'variables' => array('item' => NULL),
       'template' => 'alapjarat_mc_image',
     ),
     'alapjarat_mc_video' => array(
       'variables' => array('item' => NULL),
       'template' => 'alapjarat_mc_video',
     ),
   );
}
