---
yconfig:
  config:
    menucallback: &menucallback !menucallback
  menu:
    admin/config/development/y:
      title: YAML configuration
      description: Configure YAML configuration
      page callback: drupal_get_form
      page arguments: [ y__system_settings_form, admin, y settings form, 'y', yconfig ]
      access arguments: [ administer site configuration ]
      # << : *menucallback this is formula if yconfig.inc file exists, but y__system_settings_form has now been set in Y module

  y settings form:
    description:
      '#type': item
      '#title': !t Configure the Y Module
      '#description': !t This page is also an example of how to use the Y Module.
    y_cache_flag:
      '#type': checkbox
      '#title': !t YAML Configuration caching
      '#description': !t Turn YAML configuration caching on and off.
      '#variable_default': TRUE # creates system-wide variable which defaults to ON

...