<?php
/**
 * @file
 * the datetimepicker module file.
 */

/**
 * Implements hook_permission().
 */
function datetimepicker_permission() {
  return array(
    'administer datetimepicker' => array(
      'title' => t('Administer datetimepicker settings'),
      'description' => t('Administer datetimepicker settings.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function datetimepicker_menu() {
  $items['admin/config/datetimepicker'] = array(
    'title' => 'datetimepicker settings',
    'description' => ' Administer the datetimepicker.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('datetimepicker_settings'),
    'access arguments' => array('administer datetimepicker'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'datetimepicker.admin.inc',
    'weight' => 100,
  );
  return $items;
}

/**
 *  Implements hook_library().
 */
function datetimepicker_library() {
  $path = libraries_get_path('jquery-ui-timepicker');
  $libraries['jquery-ui-timepicker'] = array(
    'title' => 'jQuery ui timepicker',
    'website' => 'https://github.com/trentrichardson/jQuery-timepicker-Addon',
    'version' => '1.0.1',
    'js' => array(
      $path . '/jquery-ui-sliderAccess.js' => array(),
      $path . '/jquery-ui-timepicker-addon.js' => array(),
    ),
    'css' => array(
      $path . '/jquery-ui-timepicker-addon.css' => array(
        'type' => 'file',
        'media' => 'screen',
      ),
    ),
  );
  return $libraries;
}

/**
 *  Implements hook_preprocess_html().
 */
function datetimepicker_preprocess_html($variables) {
  // Dependencies from drupal core.
  drupal_add_library('system', 'ui.datepicker');
  drupal_add_library('system', 'ui.slider');
  // Dependency for this module.
  drupal_add_library('datetimepicker', 'jquery-ui-timepicker');
  // Add the settings to the page for the other datetimepicker classes.
  drupal_add_js(array(
    'timepicker' => array(
      'classes' => variable_get('timepicker_activation_class', ''),
    ),
    'datetimepicker' => array(
      'classes' => variable_get('datetimepicker_activation_class', ''),
      'default_date_format' => check_plain(variable_get('datetimepicker_default_date_format', 'yy-mm-dd')),
      'default_time_format' => check_plain(variable_get('datetimepicker_default_time_format', 'hh:mm')),
      'default_separator' => check_plain(variable_get('datetimepicker_default_separator', 'hh:mm')),
    )), 'setting');
  $path = drupal_get_path('module', 'datetimepicker');
  drupal_add_js($path . '/js/datetimepicker.js', array(
    'type' => 'file',
    'scope' => 'footer'));
}
