<?php

/*function alapjarat_preprocess_page(&$vars){
 $path = $_GET['q'];

  if (strpos($path,'kiskutya') !== false) {
    drupal_set_title('Alapjárat');
  }
}*/

function alapjarat_preprocess_html(&$vars)
{
	$vars['head_title'] = implode(' | ', array(drupal_set_title('Alapjárat')));
}

$element = array(
  '#tag' => 'link', // The #tag is the html tag - 
  '#attributes' => array( // Set up an array of attributes inside the tag
    'href' => 'https://fonts.googleapis.com/css?family=Montserrat', 
    'rel' => 'stylesheet',
    'type' => 'text/css',
  ),
);
drupal_add_html_head($element);