yvalue:
  theme:
    path: !path
    file: !local file
    variables:
      title: ""
      title_display: before
      title_tag: span
      title_attributes: { class: [ title ] }
      title_separator: ':'
      value: ''
      value_tag: span
      value_attributes: {class: [ value ] }
      wrapper_tag: div
      wrapper_attributes: { class: [ value ] }
      options: [ ]
