<?php
/*
function alapjarat_preprocess_page(&$vars){
 $path = $_GET['q'];

  if (strpos($path,'archive') !== false) {
    drupal_set_title('Alapjárat');
  }
}


function alapjarat_common_preprocess_html(&$vars) {
	$vars['head_title'] = implode(' | ', array(drupal_set_title('Alapjárat')));
}
*/

// Hidden
function alapjarat_common_form_alter(&$form, &$form_state, $form_id) {
	if($form_id == 'search_block_form') {
		hide($form['actions']['submit']);
	}
	
	if($form['#id'] == 'views-exposed-form-search-page-page') {
		hide($form['submit']);
	}

	if($form['#id'] == 'views-exposed-form-search-page-page') {
		hide($form['submit']);
	}

	if($form['#id'] == 'a-article-node-form') {
		hide($form['field_hiden_select']);
		hide($form['options']['promote']);
		hide($form['options']['sticky']);
	}

}


//Archive
function alapjarat_common_ctools_plugin_directory($owner, $plugin_type) {
	if ($owner == 'ctools' && $plugin_type == 'content_types') {
		return 'plugins/content_types';
	}
}

function alapjarat_common_article_archives_menu() {
	$dateformat = 'Y. F';

	$output = '<ul>';

	$start = date($dateformat);
	$start_y = date('Y. ');
	$start_m = date('F');

	$archive = date('Ym', strtotime($start));
	$end = date($dateformat, strtotime('2016 October'));
	
	$output .= '<li>' . l($start_y . t($start_m), 'archive/' . $archive) . '</li>';

	$prev_month = date($dateformat, strtotime('-1 month', strtotime($start)));
	$prev_y = date('Y. ', strtotime($prev_month));
	$prev_m = date('F', strtotime($prev_month));


	$c = 0;
	while ($end !== date($dateformat, strtotime('+1 month', strtotime($prev_month)))) {
		$archive = date('Ym', strtotime($prev_month));
		$prev_y = date('Y. ', strtotime($prev_month));
		$prev_m = date('F', strtotime($prev_month));

		$output .= '<li>' . l($prev_y . t($prev_m), 'archive/' . $archive) . '</li>';
		$prev_month = date($dateformat, strtotime('-1 month', strtotime($prev_month)));
		$c++;
	}
	$output .= '<ul>';


	return $output;
}

//Article
function alapjarat_common_node_presave($node) {
	if($node->type == 'a_article' && isset($node->field_title2['und']))
	{
		$node->title = strip_tags($node->field_title2['und'][0]['value']);
	}

	if($node->type == 'a_article' && !is_null($node->publish_on))
	{
		$node->sketch = 0;
		$node->scheduled = 1;
	}

	if($node->type == 'a_article' && $node->status == 1)
	{
		$node->sketch = 0;
		$node->scheduled = 0;
		$node->field_hiden_select['und'][0]['value'] = 0;
	}

	if($node->type == 'a_article' && $node->sketch == 1)
	{
		$node->field_hiden_select['und'][0]['value'] = 1;
	}


	if($node->type == 'a_article' && $node->scheduled == 1)
	{
		$node->field_hiden_select['und'][0]['value'] = 2;
	}
}

function alapjarat_common_most_popular_terms() {
	$query = db_select('field_data_field_tagsa', 't')
	->fields('t', array('field_tagsa_tid'))
	->groupBy('t.field_tagsa_tid')
	->orderBy('tc', 'DESC')
	->range(0,5);
	$query->addExpression('COUNT(t.field_tagsa_tid)', 'tc');

	$results = $query->execute();

	foreach ($results as $row) {
		$term = taxonomy_term_load($row->field_tagsa_tid);
		$items[] = l('#' . $term->name, drupal_get_path_alias('taxonomy/term/' . $term->tid));
	}

	$variables = array('items' => $items);

	return theme('item_list', array('items'=>$items));
}

